export const TelemetryEvent = {
  activate: 'activate',
  initialization: 'initialization',
  openContentDashboard: 'openContentDashboard',
  openMediaDashboard: 'openMediaDashboard',
  openDataDashboard: 'openDataDashboard',
  openSnippetsDashboard: 'openSnippetsDashboard',
  closeDashboard: 'closeDashboard',
  generateSlug: 'generateSlug',
  createContentFromTemplate: 'createContentFromTemplate',
  createContentFromContentType: 'createContentFromContentType',
  registerFolder: 'registerFolder',
  unregisterFolder: 'unregisterFolder',
  addMediaFolder: 'addMediaFolder',
  promoteSettings: 'promoteSettings',
  openPreview: 'openPreview',
  uploadMedia: 'uploadMedia',
  refreshMedia: 'refreshMedia',
  deleteMedia: 'deleteMedia',
  insertMediaToContent: 'insertMediaToContent',
  updateMediaMetadata: 'updateMediaMetadata',
  openExplorerView: 'openExplorerView',

  // Webviews
  webviewWelcomeScreen: 'webviewWelcomeScreen',
  webviewMediaView: 'webviewMediaView',
  webviewDataView: 'webviewDataView',
  webviewContentsView: 'webviewContentsView',
};