export enum DashboardMessage {
  getViewType = 'getViewType',
  getData = 'getData',
  openFile = 'openFile',
  getTheme = 'getTheme',
  createContent = 'createContent',
  createByContentType = 'createByContentType',
  createByTemplate = 'createByTemplate',
  updateSetting = 'updateSetting',
  initializeProject = 'initializeProject',
  reload = 'reload',
  setPageViewType = 'setPageViewType',
  getMedia = 'getMedia',
  copyToClipboard = 'copyToClipboard',
  refreshMedia = 'refreshMedia',
  uploadMedia = 'uploadMedia',
  deleteMedia = 'deleteMedia',
  insertPreviewImage = 'insertPreviewImage',
  updateMediaMetadata = 'updateMediaMetadata',
  createMediaFolder = 'createMediaFolder',
  setFramework = 'setFramework',
  setState = 'setState',
  runCustomScript = 'runCustomScript',
}